version: '3'

services:
  kodexplorer:
    image: xaljer/kodexplorer
    build:
      context: .
      args:
        - KODEXPLORER_VERSION=4.39
    restart: always
    ports:
      - '8006:80'
    volumes:
      - './kodexplorer-data:/var/www/html'
